-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity yuv_filter_rgb2yuv_1_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bound : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    in_channels_ch1_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    in_channels_ch1_ce0 : OUT STD_LOGIC;
    in_channels_ch1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_channels_ch2_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    in_channels_ch2_ce0 : OUT STD_LOGIC;
    in_channels_ch2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    in_channels_ch3_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    in_channels_ch3_ce0 : OUT STD_LOGIC;
    in_channels_ch3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    out_channels_ch1_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    out_channels_ch1_ce0 : OUT STD_LOGIC;
    out_channels_ch1_we0 : OUT STD_LOGIC;
    out_channels_ch1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_channels_ch2_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    out_channels_ch2_ce0 : OUT STD_LOGIC;
    out_channels_ch2_we0 : OUT STD_LOGIC;
    out_channels_ch2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_channels_ch3_address0 : OUT STD_LOGIC_VECTOR (21 downto 0);
    out_channels_ch3_ce0 : OUT STD_LOGIC;
    out_channels_ch3_we0 : OUT STD_LOGIC;
    out_channels_ch3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of yuv_filter_rgb2yuv_1_Pipeline_RGB2YUV_LOOP_X_RGB2YUV_LOOP_Y is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv9_80 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_const_lv16_FFB6 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110110110";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_FFA2 : STD_LOGIC_VECTOR (15 downto 0) := "1111111110100010";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv14_80 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_80 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_const_lv8_10 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv13_19 : STD_LOGIC_VECTOR (12 downto 0) := "0000000011001";
    constant ap_const_lv15_7FDA : STD_LOGIC_VECTOR (14 downto 0) := "111111111011010";
    constant ap_const_lv15_7A : STD_LOGIC_VECTOR (14 downto 0) := "000000001111010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln52_fu_228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln55_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln55_reg_619 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln37_fu_247_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln37_reg_624 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln57_1_fu_320_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln57_1_reg_629 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln57_1_fu_331_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln57_1_reg_634 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln57_1_reg_634_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln57_1_reg_634_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln57_1_reg_634_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln57_1_reg_634_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal R_reg_657 : STD_LOGIC_VECTOR (7 downto 0);
    signal R_reg_657_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal R_reg_657_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal B_reg_663 : STD_LOGIC_VECTOR (7 downto 0);
    signal B_reg_663_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln60_fu_336_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal G_reg_681 : STD_LOGIC_VECTOR (7 downto 0);
    signal G_reg_681_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln61_1_fu_360_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln61_fu_392_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln61_reg_698 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln62_1_fu_398_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln62_1_fu_431_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln62_1_reg_708 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln_reg_713 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln5_reg_718 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln6_reg_723 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal y_02_fu_108 : STD_LOGIC_VECTOR (15 downto 0);
    signal y_fu_255_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal x_fu_112 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln37_1_fu_280_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal indvar_flatten_fu_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln52_fu_233_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_5_fu_274_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln57_1_fu_291_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln57_fu_287_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_295_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_3_fu_303_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln57_fu_311_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln57_fu_317_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal zext_ln60_4_fu_347_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln60_3_fu_350_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln61_1_fu_360_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln60_3_fu_344_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln61_1_fu_360_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln1_fu_366_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal shl_ln61_1_fu_377_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln61_fu_373_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln61_2_fu_388_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln62_1_fu_398_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln62_1_fu_398_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln61_1_fu_384_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub_ln62_fu_404_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln2_fu_414_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln62_fu_410_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln62_1_fu_421_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub_ln62_1_fu_425_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln_fu_437_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln60_1_fu_448_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln60_2_fu_459_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln60_2_fu_455_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln60_5_fu_466_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln60_fu_470_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln60_1_fu_444_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_557_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln60_8_fu_482_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln60_1_fu_476_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln60_2_fu_485_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln61_1_fu_501_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_566_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln61_2_fu_506_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln61_2_fu_506_p2 : signal is "no";
    signal sext_ln62_1_fu_521_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_575_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln62_2_fu_524_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp48 of add_ln62_2_fu_524_p2 : signal is "no";
    signal grp_fu_557_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_557_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_557_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_566_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_566_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_575_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_575_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_557_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_557_p20 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component yuv_filter_mul_8ns_8s_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component yuv_filter_mac_muladd_8ns_5ns_9ns_13_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component yuv_filter_mac_muladd_8ns_7s_16s_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component yuv_filter_mac_muladd_8ns_7ns_16ns_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component yuv_filter_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_8ns_8s_16_1_1_U1 : component yuv_filter_mul_8ns_8s_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln61_1_fu_360_p0,
        din1 => mul_ln61_1_fu_360_p1,
        dout => mul_ln61_1_fu_360_p2);

    mul_8ns_8s_16_1_1_U2 : component yuv_filter_mul_8ns_8s_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln62_1_fu_398_p0,
        din1 => mul_ln62_1_fu_398_p1,
        dout => mul_ln62_1_fu_398_p2);

    mac_muladd_8ns_5ns_9ns_13_4_1_U3 : component yuv_filter_mac_muladd_8ns_5ns_9ns_13_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        din2_WIDTH => 9,
        dout_WIDTH => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_557_p0,
        din1 => grp_fu_557_p1,
        din2 => grp_fu_557_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_557_p3);

    mac_muladd_8ns_7s_16s_16_4_1_U4 : component yuv_filter_mac_muladd_8ns_7s_16s_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_566_p0,
        din1 => grp_fu_566_p1,
        din2 => mul_ln61_1_fu_360_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_566_p3);

    mac_muladd_8ns_7ns_16ns_16_4_1_U5 : component yuv_filter_mac_muladd_8ns_7ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_575_p0,
        din1 => grp_fu_575_p1,
        din2 => mul_ln62_1_fu_398_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_575_p3);

    flow_control_loop_pipe_sequential_init_U : component yuv_filter_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_116 <= ap_const_lv32_0;
                elsif (((icmp_ln52_fu_228_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_116 <= add_ln52_fu_233_p2;
                end if;
            end if; 
        end if;
    end process;

    x_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    x_fu_112 <= ap_const_lv16_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    x_fu_112 <= select_ln37_1_fu_280_p3;
                end if;
            end if; 
        end if;
    end process;

    y_02_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    y_02_fu_108 <= ap_const_lv16_0;
                elsif (((icmp_ln52_fu_228_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    y_02_fu_108 <= y_fu_255_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                B_reg_663 <= in_channels_ch3_q0;
                B_reg_663_pp0_iter5_reg <= B_reg_663;
                G_reg_681 <= in_channels_ch2_q0;
                G_reg_681_pp0_iter6_reg <= G_reg_681;
                R_reg_657 <= in_channels_ch1_q0;
                R_reg_657_pp0_iter5_reg <= R_reg_657;
                R_reg_657_pp0_iter6_reg <= R_reg_657_pp0_iter5_reg;
                add_ln57_1_reg_629 <= add_ln57_1_fu_320_p2;
                    add_ln62_1_reg_708(13 downto 1) <= add_ln62_1_fu_431_p2(13 downto 1);
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                    sub_ln61_reg_698(15 downto 4) <= sub_ln61_fu_392_p2(15 downto 4);
                trunc_ln5_reg_718 <= add_ln61_2_fu_506_p2(15 downto 8);
                trunc_ln6_reg_723 <= add_ln62_2_fu_524_p2(15 downto 8);
                trunc_ln_reg_713 <= add_ln60_2_fu_485_p2(15 downto 8);
                    zext_ln57_1_reg_634(21 downto 0) <= zext_ln57_1_fu_331_p1(21 downto 0);
                    zext_ln57_1_reg_634_pp0_iter4_reg(21 downto 0) <= zext_ln57_1_reg_634(21 downto 0);
                    zext_ln57_1_reg_634_pp0_iter5_reg(21 downto 0) <= zext_ln57_1_reg_634_pp0_iter4_reg(21 downto 0);
                    zext_ln57_1_reg_634_pp0_iter6_reg(21 downto 0) <= zext_ln57_1_reg_634_pp0_iter5_reg(21 downto 0);
                    zext_ln57_1_reg_634_pp0_iter7_reg(21 downto 0) <= zext_ln57_1_reg_634_pp0_iter6_reg(21 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_fu_228_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln55_reg_619 <= icmp_ln55_fu_242_p2;
                select_ln37_reg_624 <= select_ln37_fu_247_p3;
            end if;
        end if;
    end process;
    zext_ln57_1_reg_634(63 downto 22) <= "000000000000000000000000000000000000000000";
    zext_ln57_1_reg_634_pp0_iter4_reg(63 downto 22) <= "000000000000000000000000000000000000000000";
    zext_ln57_1_reg_634_pp0_iter5_reg(63 downto 22) <= "000000000000000000000000000000000000000000";
    zext_ln57_1_reg_634_pp0_iter6_reg(63 downto 22) <= "000000000000000000000000000000000000000000";
    zext_ln57_1_reg_634_pp0_iter7_reg(63 downto 22) <= "000000000000000000000000000000000000000000";
    sub_ln61_reg_698(3 downto 0) <= "0000";
    add_ln62_1_reg_708(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln52_fu_233_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_116) + unsigned(ap_const_lv32_1));
    add_ln57_1_fu_320_p2 <= std_logic_vector(unsigned(add_ln57_fu_311_p2) + unsigned(zext_ln57_fu_317_p1));
    add_ln57_fu_311_p2 <= std_logic_vector(unsigned(tmp_fu_295_p3) + unsigned(tmp_3_fu_303_p3));
    add_ln60_1_fu_476_p2 <= std_logic_vector(unsigned(add_ln60_fu_470_p2) + unsigned(zext_ln60_1_fu_444_p1));
    add_ln60_2_fu_485_p2 <= std_logic_vector(unsigned(zext_ln60_8_fu_482_p1) + unsigned(add_ln60_1_fu_476_p2));
    add_ln60_3_fu_350_p2 <= std_logic_vector(unsigned(zext_ln60_4_fu_347_p1) + unsigned(ap_const_lv9_80));
    add_ln60_fu_470_p2 <= std_logic_vector(unsigned(zext_ln60_2_fu_455_p1) + unsigned(zext_ln60_5_fu_466_p1));
    add_ln61_1_fu_501_p2 <= std_logic_vector(unsigned(sub_ln61_reg_698) + unsigned(ap_const_lv16_80));
    add_ln61_2_fu_506_p2 <= std_logic_vector(unsigned(add_ln61_1_fu_501_p2) + unsigned(grp_fu_566_p3));
    add_ln62_1_fu_431_p2 <= std_logic_vector(unsigned(sub_ln62_1_fu_425_p2) + unsigned(ap_const_lv14_80));
    add_ln62_2_fu_524_p2 <= std_logic_vector(signed(sext_ln62_1_fu_521_p1) + signed(grp_fu_575_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln52_fu_228_p2)
    begin
        if (((icmp_ln52_fu_228_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_557_p0 <= grp_fu_557_p00(8 - 1 downto 0);
    grp_fu_557_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_channels_ch3_q0),13));
    grp_fu_557_p1 <= ap_const_lv13_19(5 - 1 downto 0);
    grp_fu_557_p2 <= grp_fu_557_p20(9 - 1 downto 0);
    grp_fu_557_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln60_3_fu_350_p2),13));
    grp_fu_566_p0 <= zext_ln60_fu_336_p1(8 - 1 downto 0);
    grp_fu_566_p1 <= ap_const_lv15_7FDA(7 - 1 downto 0);
    grp_fu_575_p0 <= zext_ln60_fu_336_p1(8 - 1 downto 0);
    grp_fu_575_p1 <= ap_const_lv15_7A(7 - 1 downto 0);
    icmp_ln52_fu_228_p2 <= "1" when (indvar_flatten_fu_116 = bound) else "0";
    icmp_ln55_fu_242_p2 <= "1" when (y_02_fu_108 = p_read1) else "0";
    in_channels_ch1_address0 <= zext_ln57_1_fu_331_p1(22 - 1 downto 0);

    in_channels_ch1_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            in_channels_ch1_ce0 <= ap_const_logic_1;
        else 
            in_channels_ch1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in_channels_ch2_address0 <= zext_ln57_1_reg_634(22 - 1 downto 0);

    in_channels_ch2_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            in_channels_ch2_ce0 <= ap_const_logic_1;
        else 
            in_channels_ch2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    in_channels_ch3_address0 <= zext_ln57_1_fu_331_p1(22 - 1 downto 0);

    in_channels_ch3_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            in_channels_ch3_ce0 <= ap_const_logic_1;
        else 
            in_channels_ch3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln61_1_fu_360_p0 <= zext_ln60_3_fu_344_p1(8 - 1 downto 0);
    mul_ln61_1_fu_360_p1 <= ap_const_lv16_FFB6(8 - 1 downto 0);
    mul_ln62_1_fu_398_p0 <= zext_ln60_3_fu_344_p1(8 - 1 downto 0);
    mul_ln62_1_fu_398_p1 <= ap_const_lv16_FFA2(8 - 1 downto 0);
    out_channels_ch1_address0 <= zext_ln57_1_reg_634_pp0_iter7_reg(22 - 1 downto 0);

    out_channels_ch1_ce0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            out_channels_ch1_ce0 <= ap_const_logic_1;
        else 
            out_channels_ch1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_channels_ch1_d0 <= std_logic_vector(unsigned(trunc_ln_reg_713) + unsigned(ap_const_lv8_10));

    out_channels_ch1_we0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            out_channels_ch1_we0 <= ap_const_logic_1;
        else 
            out_channels_ch1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_channels_ch2_address0 <= zext_ln57_1_reg_634_pp0_iter7_reg(22 - 1 downto 0);

    out_channels_ch2_ce0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            out_channels_ch2_ce0 <= ap_const_logic_1;
        else 
            out_channels_ch2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_channels_ch2_d0 <= (trunc_ln5_reg_718 xor ap_const_lv8_80);

    out_channels_ch2_we0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            out_channels_ch2_we0 <= ap_const_logic_1;
        else 
            out_channels_ch2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    out_channels_ch3_address0 <= zext_ln57_1_reg_634_pp0_iter7_reg(22 - 1 downto 0);

    out_channels_ch3_ce0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            out_channels_ch3_ce0 <= ap_const_logic_1;
        else 
            out_channels_ch3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_channels_ch3_d0 <= (trunc_ln6_reg_723 xor ap_const_lv8_80);

    out_channels_ch3_we0_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            out_channels_ch3_we0 <= ap_const_logic_1;
        else 
            out_channels_ch3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln37_1_fu_280_p3 <= 
        x_5_fu_274_p2 when (icmp_ln55_reg_619(0) = '1') else 
        x_fu_112;
    select_ln37_fu_247_p3 <= 
        ap_const_lv16_0 when (icmp_ln55_fu_242_p2(0) = '1') else 
        y_02_fu_108;
        sext_ln62_1_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln62_1_reg_708),16));

        sext_ln62_fu_410_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln62_fu_404_p2),14));

    shl_ln1_fu_366_p3 <= (B_reg_663_pp0_iter5_reg & ap_const_lv7_0);
    shl_ln2_fu_414_p3 <= (B_reg_663_pp0_iter5_reg & ap_const_lv1_0);
    shl_ln60_1_fu_448_p3 <= (R_reg_657_pp0_iter6_reg & ap_const_lv1_0);
    shl_ln60_2_fu_459_p3 <= (G_reg_681_pp0_iter6_reg & ap_const_lv7_0);
    shl_ln61_1_fu_377_p3 <= (B_reg_663_pp0_iter5_reg & ap_const_lv4_0);
    shl_ln_fu_437_p3 <= (R_reg_657_pp0_iter6_reg & ap_const_lv6_0);
    sub_ln61_fu_392_p2 <= std_logic_vector(unsigned(zext_ln61_fu_373_p1) - unsigned(zext_ln61_2_fu_388_p1));
    sub_ln62_1_fu_425_p2 <= std_logic_vector(signed(sext_ln62_fu_410_p1) - signed(zext_ln62_1_fu_421_p1));
    sub_ln62_fu_404_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(zext_ln61_1_fu_384_p1));
    tmp_3_fu_303_p3 <= (trunc_ln57_fu_287_p1 & ap_const_lv8_0);
    tmp_fu_295_p3 <= (trunc_ln57_1_fu_291_p1 & ap_const_lv10_0);
    trunc_ln57_1_fu_291_p1 <= select_ln37_1_fu_280_p3(12 - 1 downto 0);
    trunc_ln57_fu_287_p1 <= select_ln37_1_fu_280_p3(14 - 1 downto 0);
    x_5_fu_274_p2 <= std_logic_vector(unsigned(x_fu_112) + unsigned(ap_const_lv16_1));
    y_fu_255_p2 <= std_logic_vector(unsigned(select_ln37_fu_247_p3) + unsigned(ap_const_lv16_1));
    zext_ln57_1_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln57_1_reg_629),64));
    zext_ln57_fu_317_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln37_reg_624),22));
    zext_ln60_1_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_437_p3),16));
    zext_ln60_2_fu_455_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln60_1_fu_448_p3),16));
    zext_ln60_3_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(G_reg_681),16));
    zext_ln60_4_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(G_reg_681),9));
    zext_ln60_5_fu_466_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln60_2_fu_459_p3),16));
    zext_ln60_8_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_557_p3),16));
    zext_ln60_fu_336_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_channels_ch1_q0),15));
    zext_ln61_1_fu_384_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln61_1_fu_377_p3),13));
    zext_ln61_2_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln61_1_fu_377_p3),16));
    zext_ln61_fu_373_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_366_p3),16));
    zext_ln62_1_fu_421_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_414_p3),14));
end behav;
