# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/smr3765/labs/Lab3_PWM_Simulation/lab_custom_ip/lab_custom_ip.srcs/sources_1/bd/lab_custom_ip/ip/lab_custom_ip_auto_pc_0/lab_custom_ip_auto_pc_0.xci
# IP: The module: 'lab_custom_ip_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/smr3765/labs/Lab3_PWM_Simulation/lab_custom_ip/lab_custom_ip.gen/sources_1/bd/lab_custom_ip/ip/lab_custom_ip_auto_pc_0/lab_custom_ip_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_custom_ip_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /scratch/smr3765/labs/Lab3_PWM_Simulation/lab_custom_ip/lab_custom_ip.srcs/sources_1/bd/lab_custom_ip/ip/lab_custom_ip_auto_pc_0/lab_custom_ip_auto_pc_0.xci
# IP: The module: 'lab_custom_ip_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/smr3765/labs/Lab3_PWM_Simulation/lab_custom_ip/lab_custom_ip.gen/sources_1/bd/lab_custom_ip/ip/lab_custom_ip_auto_pc_0/lab_custom_ip_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_custom_ip_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
