# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/lab_dma_simple/lab_dma_simple.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_dma_simple || ORIG_REF_NAME==lab_dma_simple} -quiet] -quiet

# IP: bd/lab_dma_simple/ip/lab_dma_simple_processing_system7_0_0/lab_dma_simple_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_dma_simple_processing_system7_0_0 || ORIG_REF_NAME==lab_dma_simple_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab_dma_simple/ip/lab_dma_simple_axi_dma_0_0/lab_dma_simple_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_dma_simple_axi_dma_0_0 || ORIG_REF_NAME==lab_dma_simple_axi_dma_0_0} -quiet] -quiet

# IP: bd/lab_dma_simple/ip/lab_dma_simple_auto_pc_0/lab_dma_simple_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_dma_simple_auto_pc_0 || ORIG_REF_NAME==lab_dma_simple_auto_pc_0} -quiet] -quiet

# IP: bd/lab_dma_simple/ip/lab_dma_simple_ps7_0_axi_periph_0/lab_dma_simple_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_dma_simple_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab_dma_simple_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab_dma_simple/ip/lab_dma_simple_rst_ps7_0_100M_0/lab_dma_simple_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_dma_simple_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab_dma_simple_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/lab_dma_simple/ip/lab_dma_simple_xbar_0/lab_dma_simple_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_dma_simple_xbar_0 || ORIG_REF_NAME==lab_dma_simple_xbar_0} -quiet] -quiet

# IP: bd/lab_dma_simple/ip/lab_dma_simple_auto_us_0/lab_dma_simple_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_dma_simple_auto_us_0 || ORIG_REF_NAME==lab_dma_simple_auto_us_0} -quiet] -quiet

# IP: bd/lab_dma_simple/ip/lab_dma_simple_auto_us_1/lab_dma_simple_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_dma_simple_auto_us_1 || ORIG_REF_NAME==lab_dma_simple_auto_us_1} -quiet] -quiet

# IP: bd/lab_dma_simple/ip/lab_dma_simple_auto_pc_1/lab_dma_simple_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_dma_simple_auto_pc_1 || ORIG_REF_NAME==lab_dma_simple_auto_pc_1} -quiet] -quiet

# IP: bd/lab_dma_simple/ip/lab_dma_simple_axi_mem_intercon_0/lab_dma_simple_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_dma_simple_axi_mem_intercon_0 || ORIG_REF_NAME==lab_dma_simple_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/lab_dma_simple/ip/lab_dma_simple_xlconcat_0_0/lab_dma_simple_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_dma_simple_xlconcat_0_0 || ORIG_REF_NAME==lab_dma_simple_xlconcat_0_0} -quiet] -quiet

# IP: bd/lab_dma_simple/ip/lab_dma_simple_axis_data_fifo_0_0/lab_dma_simple_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_dma_simple_axis_data_fifo_0_0 || ORIG_REF_NAME==lab_dma_simple_axis_data_fifo_0_0} -quiet] -quiet

# XDC: /scratch/smr3765/labs/lab_dma_ch/lab_dma_ch.gen/sources_1/bd/lab_dma_simple/lab_dma_simple_ooc.xdc
