# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/lab_freeRTOS/lab_freeRTOS.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_freeRTOS || ORIG_REF_NAME==lab_freeRTOS} -quiet] -quiet

# IP: bd/lab_freeRTOS/ip/lab_freeRTOS_processing_system7_0_0/lab_freeRTOS_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_freeRTOS_processing_system7_0_0 || ORIG_REF_NAME==lab_freeRTOS_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab_freeRTOS/ip/lab_freeRTOS_axi_gpio_0_0/lab_freeRTOS_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_freeRTOS_axi_gpio_0_0 || ORIG_REF_NAME==lab_freeRTOS_axi_gpio_0_0} -quiet] -quiet

# IP: bd/lab_freeRTOS/ip/lab_freeRTOS_PMOD_AD1_0_0/lab_freeRTOS_PMOD_AD1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_freeRTOS_PMOD_AD1_0_0 || ORIG_REF_NAME==lab_freeRTOS_PMOD_AD1_0_0} -quiet] -quiet

# IP: bd/lab_freeRTOS/ip/lab_freeRTOS_xbar_0/lab_freeRTOS_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_freeRTOS_xbar_0 || ORIG_REF_NAME==lab_freeRTOS_xbar_0} -quiet] -quiet

# IP: bd/lab_freeRTOS/ip/lab_freeRTOS_axi_interconnect_0_0/lab_freeRTOS_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_freeRTOS_axi_interconnect_0_0 || ORIG_REF_NAME==lab_freeRTOS_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/lab_freeRTOS/ip/lab_freeRTOS_proc_sys_reset_0_0/lab_freeRTOS_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_freeRTOS_proc_sys_reset_0_0 || ORIG_REF_NAME==lab_freeRTOS_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/lab_freeRTOS/ip/lab_freeRTOS_auto_pc_0/lab_freeRTOS_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_freeRTOS_auto_pc_0 || ORIG_REF_NAME==lab_freeRTOS_auto_pc_0} -quiet] -quiet

# XDC: /scratch/smr3765/labs/lab_freeRTOS/lab_freeRTOS.gen/sources_1/bd/lab_freeRTOS/lab_freeRTOS_ooc.xdc
