# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/gpio_const.xdc

# Block Designs: bd/lab2_gpio/lab2_gpio.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_gpio || ORIG_REF_NAME==lab2_gpio} -quiet] -quiet

# IP: bd/lab2_gpio/ip/lab2_gpio_processing_system7_0_0/lab2_gpio_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_gpio_processing_system7_0_0 || ORIG_REF_NAME==lab2_gpio_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab2_gpio/ip/lab2_gpio_axi_gpio_0_0/lab2_gpio_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_gpio_axi_gpio_0_0 || ORIG_REF_NAME==lab2_gpio_axi_gpio_0_0} -quiet] -quiet

# IP: bd/lab2_gpio/ip/lab2_gpio_ps7_0_axi_periph_1/lab2_gpio_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_gpio_ps7_0_axi_periph_1 || ORIG_REF_NAME==lab2_gpio_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/lab2_gpio/ip/lab2_gpio_rst_ps7_0_100M_1/lab2_gpio_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_gpio_rst_ps7_0_100M_1 || ORIG_REF_NAME==lab2_gpio_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/lab2_gpio/ip/lab2_gpio_xbar_0/lab2_gpio_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_gpio_xbar_0 || ORIG_REF_NAME==lab2_gpio_xbar_0} -quiet] -quiet

# IP: bd/lab2_gpio/ip/lab2_gpio_axi_gpio_0_1/lab2_gpio_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_gpio_axi_gpio_0_1 || ORIG_REF_NAME==lab2_gpio_axi_gpio_0_1} -quiet] -quiet

# IP: bd/lab2_gpio/ip/lab2_gpio_xlslice_0_0/lab2_gpio_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_gpio_xlslice_0_0 || ORIG_REF_NAME==lab2_gpio_xlslice_0_0} -quiet] -quiet

# IP: bd/lab2_gpio/ip/lab2_gpio_auto_pc_0/lab2_gpio_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab2_gpio_auto_pc_0 || ORIG_REF_NAME==lab2_gpio_auto_pc_0} -quiet] -quiet

# XDC: /scratch/smr3765/labs/lab2_gpio/lab2_gpio.gen/sources_1/bd/lab2_gpio/lab2_gpio_ooc.xdc
