# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.srcs/sources_1/bd/ComBlock/ip/ComBlock_rst_ps7_0_100M_0/ComBlock_rst_ps7_0_100M_0.xci
# IP: The module: 'ComBlock_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_rst_ps7_0_100M_0/ComBlock_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ComBlock_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_rst_ps7_0_100M_0/ComBlock_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ComBlock_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_rst_ps7_0_100M_0/ComBlock_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ComBlock_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.srcs/sources_1/bd/ComBlock/ip/ComBlock_rst_ps7_0_100M_0/ComBlock_rst_ps7_0_100M_0.xci
# IP: The module: 'ComBlock_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_rst_ps7_0_100M_0/ComBlock_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ComBlock_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_rst_ps7_0_100M_0/ComBlock_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ComBlock_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_rst_ps7_0_100M_0/ComBlock_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ComBlock_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
