# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/smr3765/labs/lab1_hw/lab1_hw.srcs/sources_1/bd/lab1_hw/ip/lab1_hw_processing_system7_0_0/lab1_hw_processing_system7_0_0.xci
# IP: The module: 'lab1_hw_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/smr3765/labs/lab1_hw/lab1_hw.gen/sources_1/bd/lab1_hw/ip/lab1_hw_processing_system7_0_0/lab1_hw_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab1_hw_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /scratch/smr3765/labs/lab1_hw/lab1_hw.srcs/sources_1/bd/lab1_hw/ip/lab1_hw_processing_system7_0_0/lab1_hw_processing_system7_0_0.xci
# IP: The module: 'lab1_hw_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/smr3765/labs/lab1_hw/lab1_hw.gen/sources_1/bd/lab1_hw/ip/lab1_hw_processing_system7_0_0/lab1_hw_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab1_hw_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
