# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/oled_constraint.xdc

# Block Designs: bd/lab_irq/lab_irq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_irq || ORIG_REF_NAME==lab_irq} -quiet] -quiet

# IP: bd/lab_irq/ip/lab_irq_processing_system7_0_0/lab_irq_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_irq_processing_system7_0_0 || ORIG_REF_NAME==lab_irq_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab_irq/ip/lab_irq_ZedboardOLED_v1_0_0_0/lab_irq_ZedboardOLED_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_irq_ZedboardOLED_v1_0_0_0 || ORIG_REF_NAME==lab_irq_ZedboardOLED_v1_0_0_0} -quiet] -quiet

# IP: ip/charLib/charLib.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# IP: bd/lab_irq/ip/lab_irq_ps7_0_axi_periph_0/lab_irq_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_irq_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab_irq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab_irq/ip/lab_irq_rst_ps7_0_100M_0/lab_irq_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_irq_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab_irq_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/lab_irq/ip/lab_irq_xbar_0/lab_irq_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_irq_xbar_0 || ORIG_REF_NAME==lab_irq_xbar_0} -quiet] -quiet

# IP: bd/lab_irq/ip/lab_irq_axi_gpio_0_0/lab_irq_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_irq_axi_gpio_0_0 || ORIG_REF_NAME==lab_irq_axi_gpio_0_0} -quiet] -quiet

# IP: bd/lab_irq/ip/lab_irq_auto_pc_0/lab_irq_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_irq_auto_pc_0 || ORIG_REF_NAME==lab_irq_auto_pc_0} -quiet] -quiet

# IP: ip/charLib/charLib.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# XDC: /scratch/smr3765/labs/lab_irq/lab_irq.gen/sources_1/bd/lab_irq/lab_irq_ooc.xdc
