# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/smr3765/labs/lab2_gpio/lab2_gpio.srcs/sources_1/bd/lab2_gpio/ip/lab2_gpio_processing_system7_0_0/lab2_gpio_processing_system7_0_0.xci
# IP: The module: 'lab2_gpio_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/smr3765/labs/lab2_gpio/lab2_gpio.gen/sources_1/bd/lab2_gpio/ip/lab2_gpio_processing_system7_0_0/lab2_gpio_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_gpio_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /scratch/smr3765/labs/lab2_gpio/lab2_gpio.srcs/sources_1/bd/lab2_gpio/ip/lab2_gpio_processing_system7_0_0/lab2_gpio_processing_system7_0_0.xci
# IP: The module: 'lab2_gpio_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/smr3765/labs/lab2_gpio/lab2_gpio.gen/sources_1/bd/lab2_gpio/ip/lab2_gpio_processing_system7_0_0/lab2_gpio_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab2_gpio_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
