# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab_custom_ip.xdc

# Block Designs: bd/lab_custom_ip/lab_custom_ip.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_custom_ip || ORIG_REF_NAME==lab_custom_ip} -quiet] -quiet

# IP: bd/lab_custom_ip/ip/lab_custom_ip_processing_system7_0_0/lab_custom_ip_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_custom_ip_processing_system7_0_0 || ORIG_REF_NAME==lab_custom_ip_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab_custom_ip/ip/lab_custom_ip_my_pwm_ip_c1_0_0/lab_custom_ip_my_pwm_ip_c1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_custom_ip_my_pwm_ip_c1_0_0 || ORIG_REF_NAME==lab_custom_ip_my_pwm_ip_c1_0_0} -quiet] -quiet

# IP: bd/lab_custom_ip/ip/lab_custom_ip_auto_pc_0/lab_custom_ip_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_custom_ip_auto_pc_0 || ORIG_REF_NAME==lab_custom_ip_auto_pc_0} -quiet] -quiet

# IP: bd/lab_custom_ip/ip/lab_custom_ip_ps7_0_axi_periph_0/lab_custom_ip_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_custom_ip_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab_custom_ip_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab_custom_ip/ip/lab_custom_ip_rst_ps7_0_100M_0/lab_custom_ip_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab_custom_ip_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab_custom_ip_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: /scratch/smr3765/labs/Lab3_PWM_Simulation/lab_custom_ip/lab_custom_ip.gen/sources_1/bd/lab_custom_ip/lab_custom_ip_ooc.xdc
