# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/smr3765/labs/lab_dma_ch/lab_dma_ch.srcs/sources_1/bd/lab_dma_simple/ip/lab_dma_simple_auto_pc_1/lab_dma_simple_auto_pc_1.xci
# IP: The module: 'lab_dma_simple_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/smr3765/labs/lab_dma_ch/lab_dma_ch.gen/sources_1/bd/lab_dma_simple/ip/lab_dma_simple_auto_pc_1/lab_dma_simple_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_dma_simple_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /scratch/smr3765/labs/lab_dma_ch/lab_dma_ch.srcs/sources_1/bd/lab_dma_simple/ip/lab_dma_simple_auto_pc_1/lab_dma_simple_auto_pc_1.xci
# IP: The module: 'lab_dma_simple_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/smr3765/labs/lab_dma_ch/lab_dma_ch.gen/sources_1/bd/lab_dma_simple/ip/lab_dma_simple_auto_pc_1/lab_dma_simple_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_dma_simple_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
