
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_PMOD_A_O_DEVICE_ID,
		XPAR_PMOD_A_O_BASEADDR,
		XPAR_PMOD_A_O_INTERRUPT_PRESENT,
		XPAR_PMOD_A_O_IS_DUAL
	},
	{
		XPAR_PMOD_B_I_DEVICE_ID,
		XPAR_PMOD_B_I_BASEADDR,
		XPAR_PMOD_B_I_INTERRUPT_PRESENT,
		XPAR_PMOD_B_I_IS_DUAL
	}
};


