# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.srcs/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/ComBlock_axi_smc_0.xci
# IP: The module: 'ComBlock_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/bd_c6c5.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_0/bd_c6c5_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_1/bd_c6c5_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_2/bd_c6c5_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_3/bd_c6c5_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_4/bd_c6c5_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_5/bd_c6c5_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_6/bd_c6c5_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_7/bd_c6c5_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_8/bd_c6c5_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_9/bd_c6c5_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_10/bd_c6c5_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_11/bd_c6c5_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_12/bd_c6c5_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_13/bd_c6c5_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_14/bd_c6c5_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_15/bd_c6c5_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_16/bd_c6c5_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_17/bd_c6c5_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_18/bd_c6c5_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_19/bd_c6c5_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_20/bd_c6c5_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_21/bd_c6c5_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_22/bd_c6c5_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_23/bd_c6c5_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_24/bd_c6c5_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_25/bd_c6c5_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_26/bd_c6c5_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_27/bd_c6c5_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_28/bd_c6c5_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_29/bd_c6c5_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_1/bd_c6c5_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_1/bd_c6c5_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_2/bd_c6c5_arsw_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_3/bd_c6c5_rsw_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_4/bd_c6c5_awsw_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_5/bd_c6c5_wsw_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_6/bd_c6c5_bsw_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_10/bd_c6c5_s00a2s_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_11/bd_c6c5_sarn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_12/bd_c6c5_srn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_13/bd_c6c5_sawn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_14/bd_c6c5_swn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_15/bd_c6c5_sbn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_16/bd_c6c5_m00s2a_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_17/bd_c6c5_m00arn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_18/bd_c6c5_m00rn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_19/bd_c6c5_m00awn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_20/bd_c6c5_m00wn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_21/bd_c6c5_m00bn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_23/bd_c6c5_m01s2a_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_24/bd_c6c5_m01arn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_25/bd_c6c5_m01rn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_26/bd_c6c5_m01awn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_27/bd_c6c5_m01wn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_28/bd_c6c5_m01bn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ComBlock_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.srcs/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/ComBlock_axi_smc_0.xci
# IP: The module: 'ComBlock_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/bd_c6c5.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_0/bd_c6c5_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_1/bd_c6c5_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_2/bd_c6c5_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_3/bd_c6c5_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_4/bd_c6c5_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_5/bd_c6c5_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_6/bd_c6c5_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_7/bd_c6c5_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_8/bd_c6c5_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_9/bd_c6c5_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_10/bd_c6c5_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_11/bd_c6c5_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_12/bd_c6c5_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_13/bd_c6c5_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_14/bd_c6c5_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_15/bd_c6c5_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_16/bd_c6c5_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_17/bd_c6c5_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_18/bd_c6c5_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_19/bd_c6c5_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_20/bd_c6c5_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_21/bd_c6c5_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_22/bd_c6c5_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_23/bd_c6c5_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_24/bd_c6c5_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_25/bd_c6c5_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_26/bd_c6c5_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_27/bd_c6c5_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_28/bd_c6c5_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_29/bd_c6c5_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_1/bd_c6c5_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_1/bd_c6c5_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_2/bd_c6c5_arsw_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_3/bd_c6c5_rsw_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_4/bd_c6c5_awsw_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_5/bd_c6c5_wsw_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_6/bd_c6c5_bsw_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_10/bd_c6c5_s00a2s_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_11/bd_c6c5_sarn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_12/bd_c6c5_srn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_13/bd_c6c5_sawn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_14/bd_c6c5_swn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_15/bd_c6c5_sbn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_16/bd_c6c5_m00s2a_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_17/bd_c6c5_m00arn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_18/bd_c6c5_m00rn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_19/bd_c6c5_m00awn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_20/bd_c6c5_m00wn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_21/bd_c6c5_m00bn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_23/bd_c6c5_m01s2a_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_24/bd_c6c5_m01arn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_25/bd_c6c5_m01rn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_26/bd_c6c5_m01awn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_27/bd_c6c5_m01wn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/bd_0/ip/ip_28/bd_c6c5_m01bn_0_ooc.xdc

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ip/ComBlock_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ComBlock_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
