# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraint/comblock_test.xdc

# Block Designs: bd/ComBlock/ComBlock.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ComBlock || ORIG_REF_NAME==ComBlock} -quiet] -quiet

# IP: bd/ComBlock/ip/ComBlock_processing_system7_0_0/ComBlock_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ComBlock_processing_system7_0_0 || ORIG_REF_NAME==ComBlock_processing_system7_0_0} -quiet] -quiet

# IP: bd/ComBlock/ip/ComBlock_comblock_0_0/ComBlock_comblock_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ComBlock_comblock_0_0 || ORIG_REF_NAME==ComBlock_comblock_0_0} -quiet] -quiet

# IP: bd/ComBlock/ip/ComBlock_c_counter_binary_0_0/ComBlock_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ComBlock_c_counter_binary_0_0 || ORIG_REF_NAME==ComBlock_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/ComBlock/ip/ComBlock_xlconstant_0_0/ComBlock_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ComBlock_xlconstant_0_0 || ORIG_REF_NAME==ComBlock_xlconstant_0_0} -quiet] -quiet

# IP: bd/ComBlock/ip/ComBlock_xlconstant_1_0/ComBlock_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ComBlock_xlconstant_1_0 || ORIG_REF_NAME==ComBlock_xlconstant_1_0} -quiet] -quiet

# IP: bd/ComBlock/ip/ComBlock_c_counter_binary_1_0/ComBlock_c_counter_binary_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ComBlock_c_counter_binary_1_0 || ORIG_REF_NAME==ComBlock_c_counter_binary_1_0} -quiet] -quiet

# IP: bd/ComBlock/ip/ComBlock_axi_smc_0/ComBlock_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ComBlock_axi_smc_0 || ORIG_REF_NAME==ComBlock_axi_smc_0} -quiet] -quiet

# IP: bd/ComBlock/ip/ComBlock_rst_ps7_0_100M_0/ComBlock_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ComBlock_rst_ps7_0_100M_0 || ORIG_REF_NAME==ComBlock_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: /scratch/smr3765/labs/lab_ComBlock/lab_ComBlock.gen/sources_1/bd/ComBlock/ComBlock_ooc.xdc
