# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /scratch/smr3765/labs/lab_dma_simple/lab_dma_simple.srcs/sources_1/bd/lab_dma_simple/ip/lab_dma_simple_axi_dma_0_0/lab_dma_simple_axi_dma_0_0.xci
# IP: The module: 'lab_dma_simple_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/smr3765/labs/lab_dma_simple/lab_dma_simple.gen/sources_1/bd/lab_dma_simple/ip/lab_dma_simple_axi_dma_0_0/lab_dma_simple_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_dma_simple_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /scratch/smr3765/labs/lab_dma_simple/lab_dma_simple.gen/sources_1/bd/lab_dma_simple/ip/lab_dma_simple_axi_dma_0_0/lab_dma_simple_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_dma_simple_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /scratch/smr3765/labs/lab_dma_simple/lab_dma_simple.gen/sources_1/bd/lab_dma_simple/ip/lab_dma_simple_axi_dma_0_0/lab_dma_simple_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_dma_simple_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /scratch/smr3765/labs/lab_dma_simple/lab_dma_simple.srcs/sources_1/bd/lab_dma_simple/ip/lab_dma_simple_axi_dma_0_0/lab_dma_simple_axi_dma_0_0.xci
# IP: The module: 'lab_dma_simple_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /scratch/smr3765/labs/lab_dma_simple/lab_dma_simple.gen/sources_1/bd/lab_dma_simple/ip/lab_dma_simple_axi_dma_0_0/lab_dma_simple_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_dma_simple_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /scratch/smr3765/labs/lab_dma_simple/lab_dma_simple.gen/sources_1/bd/lab_dma_simple/ip/lab_dma_simple_axi_dma_0_0/lab_dma_simple_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_dma_simple_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /scratch/smr3765/labs/lab_dma_simple/lab_dma_simple.gen/sources_1/bd/lab_dma_simple/ip/lab_dma_simple_axi_dma_0_0/lab_dma_simple_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab_dma_simple_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
